### ISSUE TITLE
Incompatible with symfony 3?

### ISSUE THREAD

**Issue by rfay** [Ayesh/Composer-Preload#1]
I was excited to try this out with Drupal 8, but it seems to require symfony 4, and Drupal 8 is symfony 3. That should probably go into the README.

Thanks for the excellent thinking and work on this! 

```
Using version ^0.0.4 for ayesh/composer-preload
./composer.json has been updated
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ayesh/composer-preload ^0.0.4 -> satisfiable by ayesh/composer-preload[v0.0.4].
    - Conclusion: remove symfony/finder v3.4.18
    - Conclusion: don't install symfony/finder v3.4.18
    - ayesh/composer-preload v0.0.4 requires symfony/finder ^4.1 -> satisfiable by symfony/finder[4.1.x-dev, 4.2.x-dev, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.2.0-BETA1, v4.2.0-BETA2].
    - Can only install one of: symfony/finder[4.1.x-dev, v3.4.18].
    - Can only install one of: symfony/finder[4.2.x-dev, v3.4.18].
    - Can only install one of: symfony/finder[v4.1.0, v3.4.18].
    - Can only install one of: symfony/finder[v4.1.0-BETA1, v3.4.18].
    - Can only install one of: symfony/finder[v4.1.0-BETA2, v3.4.18].
    - Can only install one of: symfony/finder[v4.1.0-BETA3, v3.4.18].
    - Can only install one of: symfony/finder[v4.1.1, v3.4.18].
    - Can only install one of: symfony/finder[v4.1.2, v3.4.18].
    - Can only install one of: symfony/finder[v4.1.3, v3.4.18].
    - Can only install one of: symfony/finder[v4.1.4, v3.4.18].
    - Can only install one of: symfony/finder[v4.1.5, v3.4.18].
    - Can only install one of: symfony/finder[v4.1.6, v3.4.18].
    - Can only install one of: symfony/finder[v4.1.7, v3.4.18].
    - Can only install one of: symfony/finder[v4.2.0-BETA1, v3.4.18].
    - Can only install one of: symfony/finder[v4.2.0-BETA2, v3.4.18].
    - Installation request for symfony/finder (locked at v3.4.18) -> satisfiable by symfony/finder[v3.4.18].
```

Drupal 8 *really* needs this :)

I'm successful with it (at the composer require level) on TYPO3 v9.

**Comment by Ayesh** [comment]
Hi Randy,
Thanks for this! I didn't realize the possible dependency conflicts. Symfony's finder is handy when we want to lookup the phone files in multiple directories, filter them with a callable, etc. 

I will see if I can do the same with Symfony 3.4, and try to loosen the composer.json requirement.

**Comment by Ayesh** [comment]
I just rolled `v0.0.5` that supports `symfony/finder:^3.4.18 | ^4.0.14 | ^4.1.7 | ^4.2.0`. The `3.4.18` should satisfy Drupal's symfony version. Thanks again for posting this issue, and I'd be grateful for any feedback.

**Comment by rfay** [comment]
Thanks! I'll give it a go.

I was thinking that this really could go in its own directory and not be mixed into the main composer.json. Then problems like this would never occur. And the preload.json could just be linked into the docroot or whatever. It might mean some duplication of code but it would forever mean you'd not have to figure out what would work for every single project this might be added to.

**Comment by rfay** [comment]
Thanks so much - I also wrote it up for [ddev](https://github.com/drud/ddev) Drupal 8 users at https://stackoverflow.com/questions/53461325/how-can-i-speed-up-my-first-few-pages-on-a-ddev-drupal-8-project/53461326#53461326

Have a couple of nits to improve the "extra" section, I'll do a PR.
