### ISSUE TITLE
Fix generated paths

### ISSUE THREAD

**Issue by snapshotpl** [Ayesh/Composer-Preload#8]
> Preload file uses absolute paths. Unless both of your servers have same directory hierarchy, you cannot do this. It is recommend not to include the vendor/preload.php file in your version control system.

But there is another case - you use build server, prepare package and upload code to server. Build server has different path. In my example I use Heroku

**Comment by kgrosvenor** [comment]
I agree, could we not set the baseUrl from the composer config and have the generator process the paths without absolute naming? My composer process is separate from my API project

**Comment by Ayesh** [comment]
Thanks for your inputs @kgrosvenor and @snapshotpl. You are right, the use of absolute paths isn't very useful with a CI server. I have updated the plugin so it creates a `$_root_directory` variable at the top of the `preload.php` file, and all opcache compile commands use relative paths based on this variable.
